# Variable Group 'ketyvault-image' was defined in the Variables tab
jobs:
- job: Job_1
  displayName: Agent job 1
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-18.04
  variables:
  - group: keyvault-image
  steps:
  - checkout: self
  - task: CopyFiles@2
    inputs:
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: replacetokens@3
    displayName: Replace tokens in *.json
    inputs:
      rootDirectory: packer
      targetFiles: '*.json'
  
  # - task: CmdLine@2
  #   inputs:
  #     script: |
  #      cat ./packer/centos.json
       
  # - task: FileTransform@1
  #   inputs:
  #     folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
  #     fileType: 'json'
  #     targetFiles: '*.json'
  - task: AzureCLI@2
    displayName: create rg
    inputs:
      azureSubscription: newserviceconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group create -l EastUS -n Packerrg123
  - task: PackerTool@0
    displayName: Use Packer 1.6.5
    inputs:
      version: 1.6.5
  - task: Packer@1
    displayName: Packer build
    inputs:
      connectedServiceType: azure
      azureSubscription: newserviceconnection
      templatePath: buildagent/centos/centos.json
      command: build
  - task: AzureCLI@2
    displayName: removerg
    inputs:
      azureSubscription: newserviceconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group delete -n Packerrg123 --yes
