# Variable Group 'ketyvault-image' was defined in the Variables tab
jobs:
- job: Job_1
  displayName: build share image
  timeoutInMinutes: 120
  variables:
  - template: variables.yml
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: base
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: replacetokens@3
    displayName: Replace tokens in *.json **/*.sh
    inputs:
      rootDirectory: base
      targetFiles: |
        *.json
        **/*.json
        **/*.sh
  - task: AzureCLI@2
    displayName: create rg
    inputs:
      azureSubscription: ''
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group create -l EastUS -n myPackerGroup'
  - task: PackerTool@0
    displayName: Use Packer 1.6.5
    inputs:
      version: 1.6.5
  - task: Packer@1
    displayName: Packer build
    inputs:
      connectedServiceType: 'azure'
      azureSubscription: ''
      templatePath: 'base/$(Imagetype)/image.json'
      command: 'build'
  - task: AzureCLI@2
    displayName: removerg
    inputs:
      azureSubscription: ''
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group delete -n myPackerGroup --yes'
